# Generated by Django 4.1.5 on 2023-03-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xarajat_nomi', models.CharField(max_length=255)),
                ('maqsadi', models.TextField()),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valyuta_turi', models.CharField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistan Sum'), ('RUB', 'Russian Ruble')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Xarajatlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsifi', models.TextField()),
                ('tannarxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sotilish_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miqdori', models.PositiveIntegerField()),
                ('ulchov_birligi', models.CharField(choices=[('kg', 'Kilogram'), ('lt', 'Litr'), ('dona', 'Dona'), ('m', 'Metr'), ('qop', 'Qop'), ('quti', 'Yashik,Qadoq')], max_length=20)),
                ('kategoriyasi', models.CharField(max_length=255)),
                ('taminotchi', models.CharField(max_length=255)),
                ('qutidagi_tovar_soni', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('manzili', models.TextField()),
                ('telefon_raqami', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('last_restocked_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
        ),
    ]
