# Generated by Django 4.1.5 on 2023-02-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='purpose',
            new_name='maqsadi',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='payment_quantity',
            new_name='miqdori',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='currency_type',
            new_name='valyuta_turi',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='expanse_name',
            new_name='xarajat_nomi',
        ),
    ]
