# Generated by Django 4.1.5 on 2023-03-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_kirim_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('ismi', models.CharField(max_length=255)),
                ('manzili', models.TextField()),
                ('telefon_raqami', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('currency_type', models.CharField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistan Sum'), ('RUB', 'Russian Ruble')], max_length=3)),
                ('order_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('types', models.CharField(choices=[('dona', 'Chakana'), ('ulgurji', 'Ulgurji')], max_length=255)),
                ('status', models.CharField(choices=[('kutilyapti', 'Kutilyapti'), ('tasdiqlandi', 'Tasdiqlandi'), ('yetkazildi', 'Yetkazildi'), ('bekor qilindi', 'Bekor qilindi')], max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
