# Generated by Django 4.1.5 on 2023-03-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('ismi', models.CharField(max_length=255)),
                ('manzili', models.TextField()),
                ('telefon_raqami', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valyuta_turi', models.CharField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistan Sum'), ('RUB', 'Russian Ruble')], max_length=3)),
                ('sana', models.DateField()),
                ('buyurtma_miqdori', models.PositiveIntegerField(default=0)),
                ('buyurtma_turi', models.CharField(choices=[('dona', 'Chakana'), ('ulgurji', 'Ulgurji')], max_length=255)),
                ('buyurtma_holati', models.CharField(choices=[('kutilyapti', 'Kutilyapti'), ('tasdiqlandi', 'Tasdiqlandi'), ('yetkazildi', 'Yetkazildi'), ('bekor qilindi', 'Bekor qilindi')], max_length=255)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
