# Generated by Django 4.1.5 on 2023-03-10 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('sana', models.DateField()),
                ('holati', models.CharField(choices=[("To'liq to'landi", "To'liq to'landi"), ("Qisman to'landi", "Qisman to'lanmadi"), ("To'lanmadi", "Umuman to'lanmadi")], max_length=20)),
                ('tulov_turi', models.CharField(choices=[('Naqd', 'Naqd'), ("Pul o'tkazish", "Pul o'tkazish yo'li bilan")], max_length=14)),
                ('valyuta_turi', models.CharField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistan Sum'), ('RUB', 'Russian Ruble')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.customer')),
            ],
        ),
    ]
